# Generated by Django 5.1.2 on 2024-11-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_program_app', '0001_initial'),
        ('posts_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='exerciseId',
        ),
        migrations.AddField(
            model_name='post',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise_program_app.exercise'),
        ),
    ]
