# Generated by Django 5.1.2 on 2024-11-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_program_app', '0001_initial'),
        ('posts_app', '0003_remove_post_exerciseid_post_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='exercise',
        ),
        migrations.AddField(
            model_name='post',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise_program_app.workout'),
        ),
    ]
