# Generated by Django 5.0.4 on 2024-05-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
