# Generated by Django 4.2.16 on 2024-11-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rating',
            new_name='meal_rating',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rating_count',
            new_name='meal_rating_count',
        ),
        migrations.AddField(
            model_name='user',
            name='workout_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='workout_rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
