# Generated by Django 5.1.2 on 2024-11-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_remove_post_exercise_post_workout'),
        ('user_auth_app', '0002_rename_rating_user_meal_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='posts_app.post'),
        ),
    ]
