# Generated by Django 4.2.16 on 2024-11-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_program_app', '0002_exercise_reps_exercise_sets'),
        ('user_auth_app', '0004_user_bookmarked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_workouts',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by_users', to='exercise_program_app.workout'),
        ),
    ]
