# Generated by Django 4.2.16 on 2024-12-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_program_app', '0003_food_ca_food_carbo_food_cholesterol_and_more'),
        ('user_auth_app', '0005_user_bookmarked_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_meals',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by_users', to='diet_program_app.meal'),
        ),
    ]
