name: General Issue Template
description: Create a new issue with this template to help us understand your needs and concerns better. 
title: "[ISSUE]"
labels: ["pending triage"]
body:

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of issue are you creating?
      options:
        - Bug Report
        - Feature Request
        - Deliverable
        - Wiki
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Please provide a detailed description of the issue.
      placeholder: Describe the issue in detail.
    validations:
      required: true


  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the issue here.
      placeholder:  
    validations:
      required: false