# Generated by Django 4.2.16 on 2024-12-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('energ_kcal', models.TextField(default='N/A')),
                ('fat', models.TextField(default='N/A')),
                ('fat_saturated', models.TextField(default='N/A')),
                ('fat_trans', models.TextField(default='N/A')),
                ('carbo', models.TextField(default='N/A')),
                ('fiber', models.TextField(default='N/A')),
                ('sugar', models.TextField(default='N/A')),
                ('protein', models.TextField(default='N/A')),
                ('cholesterol', models.TextField(default='N/A')),
                ('na', models.TextField(default='N/A')),
                ('ca', models.TextField(default='N/A')),
                ('k', models.TextField(default='N/A')),
                ('vit_k', models.TextField(default='N/A')),
                ('vit_c', models.TextField(default='N/A')),
                ('vit_a_rae', models.TextField(default='N/A')),
                ('vit_d', models.TextField(default='N/A')),
                ('vit_b12', models.TextField(default='N/A')),
                ('vit_b6', models.TextField(default='N/A')),
                ('recipe_url', models.URLField(blank=True, default='')),
                ('image_url', models.ImageField(blank=True, default='', upload_to='food_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
                ('meal_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
            ],
        ),
    ]
