# Generated by Django 4.2.16 on 2024-12-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_program_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='recipe_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
