# Generated by Django 4.2.16 on 2024-12-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_program_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ca',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='carbo',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='creator_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='energ_kcal',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='fat_saturated',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='fat_trans',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='fiber',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='food',
            name='k',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='na',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='recipe_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='food',
            name='sugar',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='vit_a_rae',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='vit_b12',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='vit_b6',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='vit_c',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='vit_d',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='food',
            name='vit_k',
            field=models.TextField(default='N/A'),
        ),
    ]
