# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=group4_admin_dbnba
ENV MYSQL_DATABASE=nba_database
ENV MYSQL_USER=group4
ENV MYSQL_PASSWORD=group4_dbnba

# Expose port 3306 to allow external connections
EXPOSE 3306