# Generated by Django 5.0.4 on 2024-05-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_app', '0003_comment'),
        ('nba_app', '0003_follow_user_following'),
        ('nba_app', '0004_alter_post_image'),
    ]

    operations = [
    ]
