# Generated by Django 4.2.16 on 2024-10-18 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseInstance',
            fields=[
                ('exercise_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('muscle', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('instruction', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('muscle', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('instruction', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_program_app.workout')),
            ],
        ),
    ]
