# Generated by Django 4.2.16 on 2024-11-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_program_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('days_per_week', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='exercise_program_app.weeklyprogram')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_program_app.workout')),
            ],
        ),
    ]
