# Generated by Django 4.2.16 on 2024-11-22 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_program_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_program_app.workout'),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='exercise_program_app.weeklyprogram'),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_program_app.workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyprogram',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_program_app.workout'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutlog',
            unique_together={('user', 'date_completed')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('program', 'day_of_week')},
        ),
    ]
