# Generated by Django 5.1.2 on 2024-11-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_program_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
