# Generated by Django 4.2.16 on 2024-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_program_app', '0002_exercise_reps_exercise_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselog',
            name='actual_reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='actual_sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
