# Generated by Django 4.2.16 on 2024-12-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_program_app', '0003_exerciseinstance_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=50),
        ),
    ]
