# Generated by Django 4.2.16 on 2024-11-18 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercise_program_app', '0003_weeklyprogram_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogram',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
