# Generated by Django 4.2.16 on 2024-12-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_program_app', '0003_exerciselog_actual_reps_exerciselog_actual_sets_and_more'),
        ('exercise_program_app', '0004_exercise_difficulty'),
    ]

    operations = [
    ]
